library:
  source-dirs: src
dependencies:
- containers
- error-util
- split
- base >= 4.7 && < 5
name: tictactoe-hs
executables:
  tictactoe-hs-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tictactoe-hs
